skin.name=lukeharby-test
skin.description=lukeharby-test
skin.language=0
skin.iconset=false
skin.frames=4
skin.menu_position=N
skin.maincontent=0
skin.mainmenu=100
skin.mainstylesheet=main.css
skin.hometx=WIDGETCONTAINERPAGE
skin.showteachbutton=yes
skin.righttoleft=false
skin.usetab=Y
skin.displaySearchBox=true
skin.fixed_width=0
skin.homepage_template=Learner9837814
skin.frameless_ui=true
skin.mouseovermenu=true
legacy.mode=true